Roles:
  - Creator
  - Validator
  - Institute
  - Vendor
  - User

Actions:
  - Creator:
    - CreateAsset.Draft
    - UpdateAsset.Draft
    - UpdateAsset.SignTxn
    - UpdateAsset.SignBlock
    - UpdateAsset.Submit
    - UpdateAsset.Publish
    - UpdateAsset.OwnershipChange
    - UpdateAsset.License
    - RemoveAsset.Unpublish
    - RemoveAsset.Delete
  - Validator:
    - ValidateAsset.Approve
    - ValidateAsset.Reject
    - ValidateAsset.SignTxn
    - ValidateAsset.SignBlock
    - CreateLicense.SignTxn
    - CreateLicense.SignBlock
    - CreateWitness.SignTxn
    - CreateWitness.SignBlock
  - Institute:
    - SingleOffering.Request
    - SingleOffering.Assign
    - SingleOffering.SignTxn
    - SingleOffering.SignBlock
    - GroupOffering.Request
    - GroupOffering.Assign
    - GroupOffering.SignTxn
    - GroupOffering.SignBlock
  - Vendor:
    - SingleAsset.Request
    - SingleAsset.Assign
    - SingleAsset.SignTxn
    - SingleAsset.SignBlock
    - GroupAsset.Request
    - GroupAsset.Assign
    - GroupAsset.SignTxn
    - GroupAsset.SignBlock
    - SingleOffering.Create.Draft
    - SingleOffering.Update.Draft
    - SingleOffering.Update.SignTxn
    - SingleOffering.Update.SignBlock
    - SingleOffering.Request.RequestLicense
    - SingleOffering.Assign.SingleLicense
    - SingleOffering.Assign.GroupLicense
    - SingleOffering.Remove.Unpublish
    - SingleOffering.Remove.Delete
    - GroupOffering.Create.Draft
    - GroupOffering.Update.Draft
    - GroupOffering.Update.SignTxn
    - GroupOffering.Update.SignBlock
    - GroupOffering.Request.RequestLicense
    - GroupOffering.Assign.SingleLicense
    - GroupOffering.Assign.GroupLicense
    - GroupOffering.Remove.Unpublish
    - GroupOffering.Remove.Delete
  - User:
    - Offering.RequestLicense
    - Offering.AcceptLicense
    - Offering.DesolveLicense
    - Offering.ConsumeLicense
    - Offering.ReturnLicense