package core

const (
	TXN_GENESIS                  = "genesis"
	TXN_ADD_GATEWAY              = "add_gateway"
	TXN_ASSERT_LOCATION          = "assert_location"
	TXN_CHAIN_VARS               = "chain_vars"
	TXN_CONSENSUS_GROUP          = "consensus_group"
	TXN_CREATE_POC_REQUEST       = "create_proof_of_coverage_request"
	TXN_DATA_CREDITS             = "data_credits"
	TXN_GENESIS_GATEWAY          = "genesis_gateway"
	TXN_MULTI_PAYMENT            = "muilti_payment"
	TXN_CREATE_OUI               = "OUI"
	TXN_PAYMENT                  = "payment"
	TXN_POC_RECIPT               = "proof_of_coverage_receipts"
	TXN_REDEEM_HASHED_TIMELOCK   = "redeem_hashed_timelock"
	TXN_REWARD                   = "reward"
	TXN_REWARDS                  = "rewards"
	TXN_ROUTING                  = "routing"
	TXN_SECURITY_COINBASE        = "security_coinbase"
	TXN_SECURITY_EXCHANGE        = "security_exchange"
	TXN_STATE_OPEN               = "state_channel_open"
	TXN_STATE_CLOSE              = "state_channel_close"
	TXN_TOKEN_BURN_EXCHANGE_RATE = "token_burn_exchange_rate"
)
